// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oevsydwmwskbguqcrdeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldnN5ZHdtd3NrYmd1cWNyZGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDk1NjIsImV4cCI6MjA1ODE4NTU2Mn0.Ii8AwF7rfnNcqMhYjqH6MawIA_yRqmF8dcuNsH4267E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);